### ISSUE TITLE
Who someone else is having this problem?

### ISSUE THREAD

**Issue by vayala** [filippogiruzzi/voice_activity_detection#6]
I have run it on Ubuntu and Windows, however, it appears this error.

![image](https://user-images.githubusercontent.com/38110052/80433242-f9d57800-88bb-11ea-9d51-52f4cbf625f7.png)

Can someone help with that?

**Comment by vayala** [comment]
I had to change from Librosa 0.7.2 to a previous one as follow:

tensorflow==1.12.0
numpy
matplotlib
seaborn
scipy
soundfile
librosa==0.7.1
tqdm
tabulate

The above solved my issue. I hope that someone can help that.

**Comment by aidosRepoint** [comment]
> I had to change from Librosa 0.7.2 to a previous one as follow:
> 
> tensorflow==1.12.0
> numpy
> matplotlib
> seaborn
> scipy
> soundfile
> librosa==0.7.1
> tqdm
> tabulate
> 
> The above solved my issue. I hope that someone can help that.

Hi!

I had the same issue. I replace 512 with 254. I think it is actually possible to change `size` to something obtained from librosa and multiplied by 2 in, 
`features = extract_features(signal_to_process, freq=16000, n_mfcc=5, size=254, step=16)`

**Comment by Pikoyooo** [comment]
Did you have this error before?
![1](https://user-images.githubusercontent.com/62178330/81642762-b0a62c00-9456-11ea-923d-17a3fe5613a8.png)
![2](https://user-images.githubusercontent.com/62178330/81642766-b3088600-9456-11ea-9f1f-48e324e539d0.png)

**Comment by Pikoyooo** [comment]
I always get errors on the path when I run in windows like
![image](https://user-images.githubusercontent.com/62178330/81667500-e9a1c900-9475-11ea-82d0-731b793b4063.png)

**Comment by vayala** [comment]
First of all -- all you need is to install Anaconda and create an environment that has the Python version that is required by the project. You can find on Google how to do that. By the way, you have to check it out that the librosa version is 0.7.1.

Once that you've done that, it's important that you download the dataset that is on this website: "https://openslr.org/12/" and you have to download the "test-clean.tar.gz" file and unzip it. Further, you need to download the exported model that gives you the project & you can download it from here "https://drive.google.com/drive/folders/1ZPQ6wnMhHeE7XP5dqpAEmBAryFzESlin".

You also can download the "labels folder" but it's not necessary to test the model. You only download the "exported folder". When you finish doing this. Please, add them (labels & exported folder) to the "vad folder" that is into the project folder.

The problem that you are having is because you need to download the "labels folder" and make sure that you have read the instructions correctly patiently.

If you have more doubts, please just write to me here. I'm happy to help you out.

**Comment by Pikoyooo** [comment]
> First of all -- all you need is to install Anaconda and create an environment that has the Python version that is required by the project. You can find on Google how to do that. By the way, you have to check it out that the librosa version is 0.7.1.
> 
> Once that you've done that, it's important that you download the dataset that is on this website: "https://openslr.org/12/" and you have to download the "test-clean.tar.gz" file and unzip it. Further, you need to download the exported model that gives you the project & you can download it from here "https://drive.google.com/drive/folders/1ZPQ6wnMhHeE7XP5dqpAEmBAryFzESlin".
> 
> You also can download the "labels folder" but it's not necessary to test the model. You only download the "exported folder". When you finish doing this. Please, add them (labels & exported folder) to the "vad folder" that is into the project folder.
> 
> The problem that you are having is because you need to download the "labels folder" and make sure that you have read the instructions correctly patiently.
> 
> If you have more doubts, please just write to me here. I'm happy to help you out.

Thank you so much, but I already have these two files in my program. And here's my program structure. So I'm thinking what you said is not my problem.
![image](https://user-images.githubusercontent.com/62178330/81714294-80d44400-94a9-11ea-8b77-c4e2ddcba0e3.png)

**Comment by vayala** [comment]
I already saw your problem. This is something that was not said in the installation process, then to install the VAD module is necessary to execute the setup.py that has the project. On your environment, execute this command:

                      python setup.py install

That should solve the problem. I hope that works for you.

**Comment by Pikoyooo** [comment]
> I already saw your problem. This is something that was not said in the installation process, then to install the VAD module is necessary to execute the setup.py that has the project. On your environment, execute this command:
> 
> ```
>                   python setup.py install
> ```
> 
> That should solve the problem. I hope that works for you.

Thanks a lot. That solve my problems in soe degree.
But there's still a problem in the 5.2 step.
When I execute this instruction, the result is
![111](https://user-images.githubusercontent.com/62178330/81762268-cff89400-94fe-11ea-96a1-9348b7361083.png)
I try to solve it so that I add 'vad/' to this path, but another problem comeout
![222](https://user-images.githubusercontent.com/62178330/81762318-eef72600-94fe-11ea-9e62-b551f41084e6.png)
![333](https://user-images.githubusercontent.com/62178330/81762323-f3bbda00-94fe-11ea-9513-af80da6f04f7.png)

**Comment by vayala** [comment]
Did you install python 3.6 in your environment?
Try by executing the same command but with python3:

              python setup.py install

**Comment by Pikoyooo** [comment]
> Did you install python 3.6 in your environment?
> Try by executing the same command but with python3:
> 
> ```
>           python setup.py install
> ```

My environment is 3.6, but 'python3' in command doesnot work.
![1](https://user-images.githubusercontent.com/62178330/81765779-4ef1ca80-9507-11ea-81a1-65bc9ea903da.png)

**Comment by vayala** [comment]
Please, email me with this Address:
victorayala271@gmail.com

**Comment by qiny1012** [comment]
> I had to change from Librosa 0.7.2 to a previous one as follow:
> 
> tensorflow==1.12.0
> numpy
> matplotlib
> seaborn
> scipy
> soundfile
> librosa==0.7.1
> tqdm
> tabulate
> 
> The above solved my issue. I hope that someone can help that.

I had the same issue. I change the code like this. librosa 0.7.2
    # Root Mean Square Energy
    # mel_spectogram = librosa.feature.melspectrogram(y=signal, sr=freq, n_fft=size, hop_length=step)
    # rmse = librosa.feature.rms(S=mel_spectogram, frame_length=size, hop_length=step)
    rmse = librosa.feature.rms(y=signal, frame_length=size, hop_length=step)

**Comment by filippogiruzzi** [comment]
Duplicate of #10
